import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { ribbonContextTabId } from './schema'

const here = dirname(fileURLToPath(import.meta.url))

describe('ribbon schema', () => {
  it('keeps Data as dataset IO and puts table ops on Operate like upstream', () => {
    const source = readFileSync(resolve(here, 'schema.ts'), 'utf8')
    expect(source).toContain("id: 'data.import'")
    expect(source).toContain("id: 'data.export'")
    expect(source).toContain("id: 'data.rename'")
    expect(source).toContain("id: 'data.remove'")
    expect(source).toContain("id: 'data-operate'")
    expect(source).toContain("id: 'data-export'")
    expect(source).toContain("id: 'data'")
    expect(source).toContain("id: 'operate'")
    expect(source).toContain("id: 'operate-clean'")
    expect(source).toContain("id: 'operate-filter'")
    expect(source).toContain("id: 'operate-stats'")
    expect(source).toContain("id: 'data.dropNa'")
    expect(source).toContain("id: 'data.dropDuplicates'")
    expect(source).toContain("id: 'data.fillNa'")
    expect(source).toContain("id: 'data.interpolate'")
    expect(source).toContain("id: 'data.removeOutliersIqr'")
    expect(source).toContain("id: 'data.removeOutliersZscore'")
    expect(source).toContain("id: 'data.transformSkewed'")
    expect(source).toContain("id: 'data.filterByColumn'")
    expect(source).toContain("id: 'data.eval'")
    expect(source).toContain("id: 'data.search'")
    expect(source).toContain("id: 'data.query'")
    expect(source).toContain("id: 'data.sort'")
    expect(source).toContain("id: 'data.describe'")
    expect(source).toContain("id: 'data.pivotTable'")
    expect(source).not.toContain("id: 'data.replaceValues'")
    expect(source).not.toContain("id: 'data.thresholdFilter'")
    expect(source).not.toContain("id: 'data-clean'")
    expect(source).not.toContain("id: 'data-analyze'")
    expect(source).toContain("id: 'workflow.run'")
    expect(source).toContain("id: 'workflow.stop'")
    expect(source).toContain("id: 'edit.undo'")
    expect(source).toContain("id: 'edit.redo'")
    expect(source).toContain("id: 'view.resetLayout'")
    expect(source).toContain("id: 'layout'")
    expect(source).toContain("id: 'home-file'")
    expect(source).toContain("id: 'create'")
    expect(source).toContain("id: 'view'")
    expect(source).toContain("id: 'view.showTable'")
    expect(source).toContain("id: 'view.showWorkflow'")
    expect(source).toContain("id: 'view.showFigure'")
    expect(source).toContain("id: 'view.showDatasets'")
    expect(source).toContain("id: 'view.showNodes'")
    expect(source).toContain("id: 'view.showProperties'")
    expect(source).toContain("id: 'view.showLog'")
    expect(source).toContain("id: 'workflowView'")
    expect(source).toContain("id: 'workflow.fitView'")
    expect(source).toContain("id: 'workflow.zoomIn'")
    expect(source).toContain("id: 'workflow.zoomOut'")
    expect(source).toContain("id: 'figure'")
    expect(source.indexOf("id: 'home'")).toBeLessThan(source.indexOf("id: 'data'"))
    expect(source.indexOf("title: t('ribbon.data')")).toBeLessThan(source.indexOf("id: 'view'"))
    expect(source.indexOf("id: 'view'")).toBeLessThan(source.indexOf("id: 'figure'"))
    expect(source.indexOf("id: 'figure'")).toBeLessThan(source.indexOf("id: 'operate'"))
    expect(source).toContain("id: 'chartOperate'")
    expect(source).toContain('contextual: true')
    expect(source).toContain("contextualMode: 'selection'")
    expect(source).not.toContain('contextualTitle')
    expect(source).toContain('ribbonContextTabId')
    expect(source).toContain("id: 'chart.newLine'")
    expect(source).toContain("id: 'chart.newScatter'")
    expect(source).toContain("id: 'chart.newBar'")
    expect(source).toContain("id: 'chart.newHist'")
    expect(source).toContain("id: 'chart.newSubplots'")
    expect(source).toContain("id: 'chart.exportPng'")
    expect(source).toContain("id: 'chart.exportSvg'")
    expect(source).toContain("id: 'chart.exportPdf'")
    expect(source).toContain("id: 'chart.annotateText'")
    expect(source).toContain("id: 'chart.annotateRegion'")
    expect(source).toMatch(
      /id: 'file\.new'[\s\S]*id: 'file\.open'[\s\S]*id: 'file\.save'[\s\S]*id: 'file\.saveAs'[\s\S]*id: 'file\.exit'/
    )
    expect(source).toContain("id: 'file.new'")
    expect(source).toContain("id: 'file.open'")
    expect(source).toContain("id: 'file.save'")
    expect(source).not.toContain("label: t('ribbon.open'), disabled: true")
    expect(source).toContain('disabled: !hasChart')
    expect(source).toContain('disabled: !hasFigure')
    expect(source).toContain("workflow.centerTab === 'table'")
    expect(source).toContain("workflow.centerTab === 'workflow'")
    expect(source).toContain("workflow.centerTab === 'figure'")
    expect(source).not.toContain("id: 'data.hist'")
    const commands = readFileSync(resolve(here, '../commands/registerBuiltin.ts'), 'utf8')
    expect(commands).toContain("'view.showTable'")
    expect(commands).toContain("'workflow.fitView'")
    expect(commands).toContain('showDock')
  })

  it('maps the focused workspace window to the matching contextual tab', () => {
    expect(ribbonContextTabId('table')).toBe('operate')
    expect(ribbonContextTabId('workflow')).toBe('workflow')
    expect(ribbonContextTabId('figure')).toBe('chartOperate')
  })
})
